### ISSUE TITLE
lux Werte für iobroker

### ISSUE THREAD

**Issue by stefantaust** [ansgarschulte/heytech_rest_endpoint#5]
Hallo Ansgar, könntest du noch eine Änderung vornehmen. Es ist eine extra Berechnung von den Lux werten integriert weil die originalen etwas hoch erscheinen. Kannst du diese wieder komplett entfernen damit die Steuerung wieder die original Daten „die hohen“ in iobroker. Danke Stefan

**Comment by ansgarschulte** [comment]
Wurden hier ausgiebig behandelt 😉 
https://github.com/Jey-Cee/ioBroker.heytech
